/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio13;

public class App {

    public static void main(String[] args) {
        double[] notas = new double[]{10, 4, 7, 4};
        double media = calcMedia(notas);
        System.out.println("Status do aluno: " + definirStatusAluno(media));
    }

    private static double calcMedia(double[] notas){
        double soma = 0;
        for (int i = 0; i < notas.length; i++) {
            soma += notas[i];
        }
        return soma / notas.length;
    }
    private static String definirStatusAluno(double media){
        if(media > 6){
            return "Aprovado";
        }else if(media > 4){
            return "Verificação Suplementar";
        }else{
            return "Reprovado";
        }
    }
}
