/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio7;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Informe um número inteiro não negativo:");
        int numero = scanner.nextInt();
        List<Integer> listaBase = new ArrayList<>();
        listaBase.add(0);
        listaBase.add(1);
        for (int i = 2; i < numero; i++) {
            listaBase.add(listaBase.get(i - 1) + listaBase.get(i - 2));
        }
        listaBase.forEach(n -> {
            System.out.printf("%d ", n);
        });
    }
}

