/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio17;

public class App {
  public static void main(String[] args) {
    Pessoa bisavoPaterno = new Pessoa("André", "90", null, null);
    
    Pessoa bisavoMaterno = new Pessoa("Jonas", "93", null, null);

    Pessoa avoPaternoPaterno = new Pessoa("João", "70", bisavoPaterno, null);
    Pessoa avoPaternoMaterno = new Pessoa("Maria", "68", bisavoMaterno, null);

    Pessoa avoMaternoPaterno = new Pessoa("Antônio", "72", null, null);
    Pessoa avoMaternoMaterno = new Pessoa("Catarina", "70", null, null);

    Pessoa pai = new Pessoa("Pedro", "45", avoPaternoPaterno, avoPaternoMaterno);
    Pessoa mae = new Pessoa("Ana", "42", avoMaternoPaterno, avoMaternoMaterno);

    Pessoa filho = new Pessoa("Lucas", "20", pai, mae);

    filho.mostrarArvoreGenealogica();
  }
}
