/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio6;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

public class App {
    public static void main(String[] args) {

        List<Integer> listaDeNumeros = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            int numeroAleatorio = new Random().nextInt(101);
            listaDeNumeros.add(numeroAleatorio);
        }
        int maiorNumero = Collections.max(listaDeNumeros);
        int menorNumero = Collections.min(listaDeNumeros);
        listaDeNumeros.forEach(n -> {
            System.out.print(n + " ");
        });
        System.out.println("\nMaior numero: " + maiorNumero);
        System.out.println("Menor numero: " + menorNumero);
    }
}
