/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio2;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Quantos tipos de produtos serão cadastrados:");
        int qtProdutos = scanner.nextInt();
        for (int i = 0; i < qtProdutos; i++){
            System.out.println("informe o nome do produto:");
            String nomeProduto = scanner.next();
            System.out.println("informe o preço do produto:");
            double precoProduto = scanner.nextDouble();
            System.out.println("informe a quantidade do produto:");
            int quantidadeProduto = scanner.nextInt();
            double precoFinal = precoProduto * quantidadeProduto;
            double precoFinalComDesconto = precoFinal;
            if(quantidadeProduto > 50){
                precoFinalComDesconto = precoFinal - (precoFinal * 25/100);
            }else if(quantidadeProduto > 20){
                precoFinalComDesconto = precoFinal - (precoFinal * 20/100);
            }else if(quantidadeProduto > 10){
                precoFinalComDesconto = precoFinal - (precoFinal * 10/100);
            }
            System.out.println(nomeProduto + " - Valor final: " + precoFinalComDesconto);
        }
        scanner.close();
    }
}
