/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio11;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class App {
    public static void main(String[] args) {
        List<Integer> vetor = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            vetor.add(new Random().nextInt(201));
        }

        System.out.println();
        for (int i = 0; i < vetor.size() - 1; i++) {
            for (int j = 0; j < vetor.size() - i - 1; j++) {
                if (vetor.get(j) > vetor.get(j + 1)) {
                    int aux = vetor.get(j);
                    vetor.set(j, vetor.get(j + 1));
                    vetor.set(j + 1, aux);
                }
            }
        }
        
        System.out.println("Lista ordenada:");
        for (int i = 0; i < 100; i++) {
            System.err.printf("%d ", vetor.get(i));
        }

    }
}
