/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio4;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String menu = """
                -----------------------
                Escolha uma das opções:
                -----------------------
                [+] - Soma
                [-] - Subtração
                [*] - Multiplicação
                [/] - Divisão
                -----------------------
                """;
        System.out.println(menu);
        char operacao = scanner.next().charAt(0);
        double n1 = scanner.nextDouble();
        double n2 = scanner.nextDouble();

        switch (operacao) {
            case '+':
                System.out.println("Resultado: " + (n1 + n2));
                break;
            case '-':
                System.out.println("Resultado: " + (n1 - n2));

                break;
            case '*':
                System.out.println("Resultado: " + (n1 * n2));

                break;
            case '/':
                if(n2 == 0){
                    System.out.println("Não é possível dividir por zero");
                    break;
                }
                System.out.println("Resultado: " + (n1 / n2));

                break;

            default:
                System.out.println("Oparador inválido");

                break;
        }
        scanner.close();
    }
}
