/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio15;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String menu = """
                -----------------------
                Escolha uma das opções:
                -----------------------
                [+] - Soma
                [-] - Subtração
                [*] - Multiplicação
                [/] - Divisão
                [^] - Potenciação
                -----------------------
                """;
        System.out.println(menu);
        char operacao = scanner.next().charAt(0);
        System.out.println("Insira o primeiro valor: ");
        double n1 = scanner.nextDouble();
        System.out.println("Insira o segundo valor: ");
        double n2 = scanner.nextDouble();

        switch (operacao) {
            case '+':
                soma(n1, n2);
                break;
            case '-':
                subtracao(n1, n2);
                break;
            case '*':
                multiplicacao(n1, n2);
                break;
            case '/':
                divisao(n1, n2);
                break;
            case '^':
                potenciacao(n1, n2);
                break;
            default:
                System.out.println("Oparador inválido");

                break;
        }
        scanner.close();
    }

    private static void soma(double n1, double n2) {
        System.out.println("Resultado: " + (n1 + n2));
    }

    private static void subtracao(double n1, double n2) {
        System.out.println("Resultado: " + (n1 - n2));
    }

    private static void multiplicacao(double n1, double n2) {
        System.out.println("Resultado: " + (n1 * n2));
    }

    private static void divisao(double n1, double n2) {
        if (n2 == 0) {
            System.out.println("Não é possível dividir por zero.");
            return;
        }
        System.out.println("Resultado: " + (n1 / n2));
    }

    private static void potenciacao(double base, double expoente) {
        System.out.println("Resultado: " + Math.pow(base, expoente));
    }
}
