/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio10;

import java.util.Random;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Determine o tamanho da matriz quadrada(valor inteiro):");
        int tamanho = scanner.nextInt();
        int somaDiagonalPrincipal = 0;
        int[][] matriz = new int[tamanho][tamanho];
        for (int i = 0; i < tamanho; i++) {
            for (int j = 0; j < tamanho; j++) {
                System.out.printf("Determina o valor da posição [%d][%d]", i+1, j+1);
                matriz[i][j] = scanner.nextInt();
            }
        }

        for (int i = 0; i < tamanho; i++) {
            for (int j = 0; j < tamanho; j++) {
                if(i == j ){
                    somaDiagonalPrincipal += matriz[i][j];
                }

            }
        }
        System.out.println("Soma da diagonal principal: " + somaDiagonalPrincipal);
        scanner.close();
    }
}
