/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio20;

import exercicio20.estoque.Estoque;
import exercicio20.menu.Menu;
import exercicio20.pedido.Pedido;
import java.util.Scanner;
import java.util.NoSuchElementException;
import java.util.InputMismatchException;

public class App {
    public static void main(String[] args) {
        Estoque estoque = new Estoque();
        estoque.inicializaEstoque();

        Menu menu = new Menu();
        Pedido pedido = new Pedido();
        Scanner scanner = new Scanner(System.in);
        while (true) {
            try {
                menu.controlaMenu(estoque, pedido, scanner);
            } catch (IllegalArgumentException e) {
                System.out.println("\n" + e.getMessage() + "\n");
            } catch (InputMismatchException e) {
                if(scanner.hasNext()){
                    scanner.next();
                }
                System.out.println("\nHouve um erro:" + e.getMessage() + "\n");
            } catch (NoSuchElementException e) {
                System.out.println("\nHouve um erro:" + e.getMessage() + "\n");
            } catch (RuntimeException e) {
                System.out.println("\nHouve um erro:" + e.getMessage() + "\n");
            }
        }

    }
}
