/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio14;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int segundos = lerSegundos(scanner);
        int horasFinais = calcularHoras(segundos);
        int minutosFinais = calcularMinutos(segundos);
        int segundosFinais = calcularSegundos(segundos);
        retornoDeDados(segundos, horasFinais, minutosFinais, segundosFinais);
        
    }
    private static int lerSegundos(Scanner scanner){
        System.out.println("Insira o tempo em segundos:");
        return scanner.nextInt();
    }
    private static void retornoDeDados(int segundos, int horas, int minutos, int segundosFinais){
        System.out.printf("%d segundos equivalem a %dh%dmin%dseg", segundos, horas, minutos, segundosFinais);
    }

    private static int calcularHoras(int segundos){
        return segundos / 3600;
    }

    private static int calcularMinutos(int segundos){
        int segundosRestantes = segundos % 3600;
        return segundosRestantes / 60;
    }
    private static int calcularSegundos(int segundos){
        int segundosDepoisDeRemoverHoras = segundos % 3600;
        return segundosDepoisDeRemoverHoras % 60;
    }
    
}
