/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio18;

public class App {
    public static void main(String[] args) {
        Carro meuCarro = new Carro(4, 180, "vermelho", 4);
        CarroAutomatico meuCarroAutomatico = new CarroAutomatico(4, 200, "azul", 4);
        Moto minhaMoto = new Moto(2, 250, "preto", 600);
        MotoPartidaPedal minhaMotoPartidaPedal = new MotoPartidaPedal(2, 200, "azul", 400);
        Guincho meuGuincho = new Guincho(4, 120, "amarelo");
        Automovel outroGuincho = new Guincho(6, 100, "verde");

        meuCarroAutomatico.ligar();
        meuCarroAutomatico.freiar();
        meuCarroAutomatico.ligar();

        minhaMotoPartidaPedal.ligar();
        minhaMotoPartidaPedal.acelerar();
        minhaMotoPartidaPedal.ligar();

        meuGuincho.rebocarAutomovel(meuCarroAutomatico);








    }
}
