/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio1;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Insira sua idade:");
        int age =  scanner.nextInt();
        boolean validation = age >= 18;
        scanner.close();
        if(validation) {
            System.out.println("Maior de idade");
            return;
        }
        System.out.println("Menor de idade");
    }
}
