/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio8;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        int numero;
        Scanner scanner = new Scanner(System.in);
        do {
            System.out.println("Digite um número inteiro");
            numero = scanner.nextInt();
            
        } while (numero != 10);
        scanner.close();
    }
}
