/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio12;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class App {

    public static void main(String[] args) {
        List<Integer> vetor1 = new ArrayList<>();
        List<Integer> vetor2 = new ArrayList<>();
        List<Integer> vetorFinal = new ArrayList<>();
        for (int i = 0; i < 50; i++) {
            vetor1.add(new Random().nextInt(201));
        }
        for (int i = 0; i < 50; i++) {
            vetor2.add(new Random().nextInt(201));
        }
        for (int i = 0; i < vetor1.size() - 1; i++) {
            for (int j = 0; j < vetor1.size() - i - 1; j++) {
                if (vetor1.get(j) > vetor1.get(j + 1)) {
                    int aux = vetor1.get(j);
                    vetor1.set(j, vetor1.get(j + 1));
                    vetor1.set(j + 1, aux);
                }
            }
        }
        for (int i = 0; i < vetor2.size() - 1; i++) {
            for (int j = 0; j < vetor2.size() - i - 1; j++) {
                if (vetor2.get(j) > vetor2.get(j + 1)) {
                    int aux = vetor2.get(j);
                    vetor2.set(j, vetor2.get(j + 1));
                    vetor2.set(j + 1, aux);
                }
            }
        }

        for (int i = 0; i < 50; i++) {
            vetorFinal.add(vetor1.get(i));
        }
        for (int i = 0; i < 50; i++) {
            vetorFinal.add(vetor2.get(i));
        }

        System.out.println();
        for (int i = 0; i < vetorFinal.size() - 1; i++) {
            for (int j = 0; j < vetorFinal.size() - i - 1; j++) {
                if (vetorFinal.get(j) > vetorFinal.get(j + 1)) {
                    int aux = vetorFinal.get(j);
                    vetorFinal.set(j, vetorFinal.get(j + 1));
                    vetorFinal.set(j + 1, aux);
                }
            }
        }
        System.out.println("Lista ordenada:");
        for (int i = 0; i < 100; i++) {
            System.err.printf("%d ", vetorFinal.get(i));
        }
    }
}
